F/mentor_finder/urls.py
from django.urls import path

from . import views

app_name = 'mentor_finder'
urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.CreateMentor.as_view(), name='create')
]

F/sampleproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mentor_finder.urls', namespace='mentor_finder'))
]

F/mentor_finder/models.py
from django.db import models


class Mentor(models.Model):
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    phone = models.PositiveSmallIntegerField()
    available = models.BooleanField()

F/mentor_finder/forms.py
from django.forms import ModelForm

from .models import Mentor


class CreateMentorForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(CreateMentorForm, self).__init__(*args, **kwargs)
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['first_name'].widget.attrs['class'] = 'form-control'
        self.fields['last_name'].widget.attrs['class'] = 'form-control'
        self.fields['phone'].widget.attrs['class'] = 'form-control'
        self.fields['available'].widget.attrs['class'] = 'form-check-input'

    class Meta:
        model = Mentor
        fields = ['email', 'first_name', 'last_name', 'phone', 'available',]

F/mentor_finder/views.py
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.views.generic.edit import FormView

from .models import Mentor
from .forms import CreateMentorForm


def index(request):
    return render(request, 'mentor_finder/index.html')


class CreateMentor(FormView):
    form_class = CreateMentorForm
    template_name = 'mentor_finder/create.html'

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            form.save()
            name = f'{form.cleaned_data["first_name"]} {form.cleaned_data["last_name"]}'
            messages.add_message(request, messages.SUCCESS,
                                 f'Successfully added {name}')
            return HttpResponseRedirect(reverse('mentor_finder:create'))

        messages.add_message(request, messages.ERROR,
                             f'An error occurred while attempting to add mentor')
        return render(request, self.template_name, {'form': form})

F/mentor_finder/templates/mentor_finder/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% block head %}

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	{% endblock %}
</head>

<body>
	<div class="container">
		<!-- Navigation -->
		<div class="header">
			{% include 'mentor_finder/nav.html' %}
		</div>

		{% if messages %}
		{% for message in messages %}
			{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
			<div class="alert alert-danger" role="alert">
			{% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
			<div class="alert alert-success" role="alert">
			{% else %}
			<div class="alert alert-primary" role="alert">
			{% endif %}
				<span{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</span>
			</div>
		{% endfor %}
		{% endif %}
		{% block content %}{% endblock %}
	</div>
	{% block scripts %}{% endblock %}
</body>

</html>

F/mentor_finder/templates/mentor_finder/create.html
{% extends "mentor_finder/base.html" %}

{% block title %}Add Mentor{% endblock %}
{% block content %}

<h1>Sign Up</h1>
<p class="lead">Enter your information below to sign up to become a mentor!</p>

<form action="create" method="post">
	{% csrf_token %}
	{{ form.non_field_errors }}
	<div class="form-group">
		{{ form.email.errors }}
		{{ form.email.label_tag }}
		{{ form.email }}
	</div>
	<div class="form-group">
		{{ form.first_name.errors }}
		{{ form.first_name.label_tag }}
		{{ form.first_name }}
	</div>
	<div class="form-group">
		{{ form.last_name.errors }}
		{{ form.last_name.label_tag }}
		{{ form.last_name }}
	</div>
	<div class="form-group">
		{{ form.phone.errors }}
		{{ form.phone.label_tag }}
		{{ form.phone }}
	</div>
	<div class="form-group form-check">
		{{ form.available.errors }}
		{{ form.available }}
		<label for="{{ form.available.id_for_label }}">Available weekends?</label>
	</div>
	<button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

F/mentor_finder/templates/mentor_finder/index.html
{% extends "mentor_finder/base.html" %}

{% block title %}Mentor Finder{% endblock %}
{% block content %}
<div class="jumbotron">
	<h1 class="display-4">Hello!</h1>
	<p class="lead">This is a sample Django application.</p>
	<hr class="my-4">
	<p>It follows the standard Django tutorial and allows users to find and sign-up as mentors.</p>
	<a class="btn btn-primary btn-lg" href="{% url 'mentor_finder:create' %}" role="button">Get started!</a>
</div>
{% endblock %}

F/mentor_finder/templates/mentor_finder/nav.html
<nav class="navbar navbar-expand-lg navbar-light">
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
		aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'mentor_finder:index' %}">Home</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'mentor_finder:create' %}">Sign Up</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Find a Mentor</a>
			</li>
		</ul>
	</div>
</nav>